### ISSUE TITLE
Disabling the sockets hook doesn't work

### ISSUE THREAD

**Issue by rishabhmhjn** [balderdashy/sails-hook-sockets#16]
Disabling the `sockets` hook doesn't seem to be working!

######  `.sailsrc`
```
{
  "hooks": {
    "blueprints": false,
    "http": false,
    "sockets": false,
    "policies": false,
    "views": false,
    "pubsub": false,
    "request": false,
    "responses": false,
    "controllers": false,
    "csrf": false,
    "cors": false,
    "session": false
  },
  "generators": {
    "modules": {}
  },
  "log": {
    "noShip": true
  }
}
```

###### my log
```
error: A hook (`sockets`) failed to load!
{ [Error (SAILS:HOOK:SOCKETS:DEPENDS_ON_HOOK):: Cannot use `sockets` hook without the `http` hook.]
  code: 'SAILS:HOOK:SOCKETS:DEPENDS_ON_HOOK',
  name: 'Error (SAILS:HOOK:SOCKETS:DEPENDS_ON_HOOK):',
  status: 500,
  message: 'Cannot use `sockets` hook without the `http` hook.',
  stack: 'Error (SAILS:HOOK:SOCKETS:DEPENDS_ON_HOOK):: Cannot use `sockets` hook without the `http` hook.
      at new constructor (/path/to/app/node_modules/sails-hook-sockets/standalone/create-error-constructor.js:38:16)
      at Errorpack.factory [as DEPENDS_ON_HOOK] (/path/to/app/node_modules/sails-hook-sockets/standalone/create-error-factory.js:34:12)
      at waitForOtherHooks (/path/to/app/node_modules/sails-hook-sockets/lib/initialize.js:41:31)
      at Hook.initialize (/path/to/app/node_modules/sails-hook-sockets/lib/initialize.js:55:7)
      at Hook.bound [as initialize] (/path/to/app/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
      at /path/to/app/node_modules/sails/lib/hooks/index.js:74:14
      at /path/to/app/node_modules/sails/node_modules/async/lib/async.js:451:17
      at /path/to/app/node_modules/sails/node_modules/async/lib/async.js:441:17
      at _each (/path/to/app/node_modules/sails/node_modules/async/lib/async.js:46:13)
      at Immediate.taskComplete (/path/to/app/node_modules/sails/node_modules/async/lib/async.js:440:13)
      at processImmediate [as _immediateCallback] (timers.js:384:17)' }
```

PS: related to https://github.com/balderdashy/sails/issues/781

**Comment by sgress454** [comment]
What version of Sails are you using, and how are you trying to start it?  Are you using any other custom config?

**Comment by rishabhmhjn** [comment]
sails version `0.11.3`
I am trying `lift`, `node app` and don't think I use any other config!

**Comment by sgress454** [comment]
Hm, I don't get that error.  What version of Node are you using?

Also, can you talk more about what you're trying to accomplish?  Running `sails lift` on the command line with the http hook disabled won't get you much.  If you're trying this programmatically, then you probably want `sails.load(...)` rather than `sails.lift(...)`.

**Comment by rishabhmhjn** [comment]
@sgress454 I was trying to run a sails instance for my cron based task where I don't require `http`

You are right, my main implementation does use `sails.load` which is failing if I set `http: false` in the rc file.


##### `batch.js`
```
  ....
  // Start server
  sails.load(rc('sailsbatch'), function(err) {
    console.log(err);
    console.log(sails.config);
    process.exit();
  });
  ....
```

##### `.sailsbatchrc`
```
{
  "hooks": {
    "http": false,
    "blueprints": false,
    "sockets": false,
    "policies": false,
    "views": false,
    "pubsub": false,
    "request": false,
    "responses": false,
    "controllers": false,
    "csrf": false,
    "cors": false,
    "session": false,
    "grunt": false
  },
  "generators": {
    "modules": {}
  },
  "log": {
    "noShip": true
  }
}
```

##### `$ node batch.js` log
```
verbose: logger hook loaded successfully.
verbose: Loading the app's models and adapters...
verbose: Loading app models...
verbose: Loading app adapters...
error: A hook (`sockets`) failed to load!
{ [Error (SAILS:HOOK:SOCKETS:DEPENDS_ON_HOOK):: Cannot use `sockets` hook without the `http` hook.]
  code: 'SAILS:HOOK:SOCKETS:DEPENDS_ON_HOOK',
  name: 'Error (SAILS:HOOK:SOCKETS:DEPENDS_ON_HOOK):',
  status: 500,
  message: 'Cannot use `sockets` hook without the `http` hook.',
  stack: 'Error (SAILS:HOOK:SOCKETS:DEPENDS_ON_HOOK):: Cannot use `sockets` hook without the `http` hook.
      at new constructor (/path/to/app/node_modules/sails-hook-sockets/standalone/create-error-constructor.js:38:16)
      at Errorpack.factory [as DEPENDS_ON_HOOK] (/path/to/app/node_modules/sails-hook-sockets/standalone/create-error-factory.js:34:12)
      at waitForOtherHooks (/path/to/app/node_modules/sails-hook-sockets/lib/initialize.js:41:31)
      at Hook.initialize (/path/to/app/node_modules/sails-hook-sockets/lib/initialize.js:55:7)
      at Hook.bound [as initialize] (/path/to/app/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
      at /path/to/app/node_modules/sails/lib/hooks/index.js:74:14
      at /path/to/app/node_modules/sails/node_modules/async/lib/async.js:451:17
      at /path/to/app/node_modules/sails/node_modules/async/lib/async.js:441:17
      at _each (/path/to/app/node_modules/sails/node_modules/async/lib/async.js:46:13)
      at Immediate.taskComplete (/path/to/app/node_modules/sails/node_modules/async/lib/async.js:440:13)
      at processImmediate [as _immediateCallback] (timers.js:384:17)' }
```

Node `v5.2.0`

**Comment by mikermcneil** [comment]
@rishabhmhjn hmm... that said, you should be able to use either `sails.lift()` or `sails.load()` and disable hooks without issue-- this seems to be something else.  Would you mind trying to pass in the configuration dictionary directly instead of using a custom `rc` call? I don't see why this would matter, but, you never know.  Also, if you wouldn't mind passing in `globals: false`, that helps rule things out.  Finally, could you post the entire contents of the `batch.js` file?  I think that'd help us make sure there aren't any issues related to race conditions, and it would be helpful in getting to the bottom of the problem since we're having trouble recreating it.  Thanks!

**Comment by rishabhmhjn** [comment]
Apologies for the delay


###### `batch.js`
```js
process.chdir(__dirname);

// Ensure a "sails" can be located:
(function() {
  var sails;
  try {
    sails = require('sails');
  } catch (e) {
    console.error('To run an app using `node app.js`, you usually need to have a version of `sails` installed in the same directory as your app.');
    console.error('To do that, run `npm install sails`');
    console.error('');
    console.error('Alternatively, if you have sails installed globally (i.e. you did `npm install -g sails`), you can use `sails lift`.');
    console.error('When you run `sails lift`, your app will still use a local `./node_modules/sails` dependency if it exists,');
    console.error('but if it doesn\'t, the app will run with the global sails instead!');
    return;
  }

  // Try to get `rc` dependency
  var rc;
  try {
    rc = require('rc');
  } catch (e0) {
    try {
      rc = require('sails/node_modules/rc');
    } catch (e1) {
      console.error('Could not find dependency: `rc`.');
      console.error('Your `.sailsrc` file(s) will be ignored.');
      console.error('To resolve this, run:');
      console.error('npm install rc --save');
      rc = function() {
        return {};
      };
    }
  }

  // Start server
  sails.lift(rc('sailsbatch'));
})();
```

###### `.sailsbatchrc`
```json
{
  "hooks": {
    "blueprints": false,
    "http": false,
    "sockets": false,
    "policies": false,
    "views": false,
    "pubsub": false,
    "request": false,
    "responses": false,
    "controllers": false,
    "csrf": false,
    "cors": false,
    "session": false,
    "grunt": false
  },
  "generators": {
    "modules": {}
  },
  "log": {
    "noShip": true
  }
}
```

I have tried setting `globals: false`, but still no luck

**Comment by tvollstaedt** [comment]
Same issue here, unable to disable "sockets" hook with ```sails.load()``` no matter if passing hooks directly or using ```.sailsrc```.

**Comment by nilswiersema** [comment]
Same here. Cannot disable the 'sockets' hook in any way.

`verbose: Preparing socket.io...`
`verbose: sockets hook loaded successfully.`
`silly: Binding route ::  get /__getcookie (SOCKETS HOOK)`

... despite having disabled it with `sails.load()` and in `.sailsrc`.

**Comment by luislobo** [comment]
I've just fixed it. It was an issue on the moduleloader hook, since sails-hook-sockets is actually a module, although the built in module is not loaded, it was loaded as a userhook. I've added a check so that it will only load the userhook if sails.hook[hookName] !== false
/cc @mikermcneil @sgress454

**Comment by rishabhmhjn** [comment]
Thank you for the fix
